### ISSUE TITLE
Login cookie issue, unable to get User Id, please check your cookie

### ISSUE THREAD

**Issue by BrazenwePARL** [Nandaka/PixivUtil2#1406]
I followed what was said in issue 814 and tried getting the cookie on the change password section, but this still doesn't work.

Unable to get User Id, please check your cookie.
Please follow the instruction in https://github.com/Nandaka/PixivUtil2/issues/814#issuecomment-711182644
Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Unable to get User Id, please check your cookie.'), <traceback object at 0x000001F9F9D19B80>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1527, in doLogin
  File "PixivBrowserFactory.py", line 371, in loginUsingCookie
  File "PixivBrowserFactory.py", line 604, in getMyId
PixivException.PixivException: PixivException(100 Unable to get User Id, please check your cookie., hasDumpPage=Y)

Cannot Login!
press enter to exit.

**Comment by Snkea** [comment]
I'm getting this as well,

**Comment by Inverness** [comment]
Same here. Followed the directed instructions and it didn't make a difference.

**Comment by Flandre5carlet** [comment]
Same thing here after getting it to work for a few weeks while following [this comment in issue #1386 ](https://github.com/Nandaka/PixivUtil2/issues/1386#issuecomment-2536949391)

**Comment by dmo140230** [comment]
Whenever this happens to me, I find that updating the 'useragent' property at the top of the file under [Network], with the value from the request headers in network tab on Firefox fixes it, since I'm pretty sure that cloudfare is blocking requests that aren't from the latest browsers

https://files.catbox.moe/aj3pzd.png

**Comment by Snkea** [comment]
help @Nandaka

**Comment by BrazenwePARL** [comment]
Tried logging into Firefox, changing useragent, and clearing cookies now this error pops up.

Logging in, return url: https://www.pixiv.net/en/
Login successful.
Unable to get User Id, please check your cookie.
Please follow the instruction in https://github.com/Nandaka/PixivUtil2/issues/814#issuecomment-711182644
Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Unable to get User Id, please check your cookie.'), <traceback object at 0x000001F882D996C0>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1527, in doLogin
  File "PixivBrowserFactory.py", line 371, in loginUsingCookie
  File "PixivBrowserFactory.py", line 604, in getMyId
PixivException.PixivException: PixivException(100 Unable to get User Id, please check your cookie., hasDumpPage=Y)

Cannot Login!

**Comment by BurnBurnCB** [comment]
Error at doLogin(): (<class 'mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper'>, <httperror_seek_wrapper (urllib.error.HTTPError instance) at 0x257f0ca3760 whose wrapped object = <HTTPError 403: 'Forbidden'>>, <traceback object at 0x00000257F0CD5480>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1527, in doLogin
  File "PixivBrowserFactory.py", line 351, in loginUsingCookie
  File "PixivBrowserFactory.py", line 207, in open_with_retry
  File "mechanize\_mechanize.py", line 257, in open
  File "mechanize\_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

Cannot Login!


----


Strangely, yesterday it worked as normal. I had "userobots" and "enableSSLVerification" set to False as that fixed some issues last time. However, after (as usual) finishing with an account and switching to another by getting the new cookie, it has stopped working and nothing seems to fix it, not even getting an updated "usersagent".

I even tried to download the app and set it all up, no results.

On another PC it is working even after that but I'm afraid it will eventually turn non functional there too.

**Comment by BrazenwePARL** [comment]
Will this be fixed? @Nandaka

**Comment by dioporcos** [comment]
This software got neglected to the point of being unusable, and it's a massive issue because i can't just use a different one that picks up all the downloaded files without making a mess. Cultured Downloader works well at least for Fanbox, i guess it's better than nothing until this gets fixed or someone makes an updated fork.

**Comment by BrazenwePARL** [comment]
As I expected, no wonder there's like 100+ issues unsolved

**Comment by NHOrus** [comment]
Real life happens.
Attacking the developer won't fix the problem and is most likely make them drop package forever.

Stop, you two.

**Comment by dioporcos** [comment]
> Real life happens. Attacking the developer won't fix the problem and is most likely make them drop package forever.
> 
> Stop, you two.

Not attacking anyone, do you see insults or disrespect? PixivUtil2 is easily the most convenient downloader i ever used for years on end and it's truly a disgrace that it's being left behind like this, i'd unironically pay if it meant having the software maintained.

**Comment by Ridajide** [comment]
The cause of this issue is not due to any regression in the code itself, but rather cloudflare triggering the human gateway shield, requiring a browser session to validate a non-bot agent.

This is the same issue that was breaking fanbox, and was fixed over at https://github.com/Nandaka/PixivUtil2/issues/1342 by adding in support for the cloudflare validation cookies, `cf_clearance ` and `__cf_bm`.

I tried to port the fix over for cookie authorization in pixiv, but for whatever reason cloudflare continued to demand the human challenge be solved on each request.

I toyed with a potential solution, which is to actually activate a browser session via `selenium`, which would allow the user to authenticate, solve the cloudflare challenge, and capture necessary cookies that could then be used by the pixiv as a headless client. Then I realised, we may as well make this an alternate authentication system, since we could also use selenium to let the user enter their username and password, skipping the whole need to manually copy in cookies (e.g. PHPSESSID).

Before spending any time on this, it'd be good to see if there's a simpler way of baking in the cloudflare cookie solution, since it'd be a bit of work to replace the whole auth pipeline. I probably missed something when migrating the solution for fanbox. :P

This is what my failed attempt at loginUsingCookie looked like. Maybe someone could look at it and spot any obvious mistake.


```python

    def loginUsingCookie(self, login_cookie=None):
        """  Log in to Pixiv using saved cookie, return True if success """
        result = False

        if login_cookie is None or len(login_cookie) == 0:
            login_cookie = self._config.cookie

        if len(login_cookie) > 0:
            PixivHelper.print_and_log('info', 'Trying to log in with saved cookie')
            self.clearCookie()

            # Copying solution from #1342 for pixiv.net
            if self._config.cf_clearance != "":
                ck1 = http.cookiejar.Cookie(version=0, name='cf_clearance', value=self._config.cf_clearance, port=None,
                                            port_specified=False, domain='www.pixiv.net', domain_specified=True,
                                            domain_initial_dot=False, path='/', path_specified=True,
                                            secure=False, expires=None, discard=True, comment=None,
                                            comment_url=None, rest={'HttpOnly': None}, rfc2109=False)
                self.addCookie(ck1)
            if self._config.cf_bm != "":
                ck2 = http.cookiejar.Cookie(version=0, name='__cf_bm', value=self._config.cf_bm, port=None,
                                            port_specified=False, domain='www.pixiv.net', domain_specified=True,
                                            domain_initial_dot=False, path='/', path_specified=True,
                                            secure=False, expires=None, discard=True, comment=None,
                                            comment_url=None, rest={'HttpOnly': None}, rfc2109=False)
                self.addCookie(ck2)


            self._loadCookie(login_cookie, "pixiv.net")
            res = self.open_with_retry('https://www.pixiv.net')  # + self._locale)
            parsed = BeautifulSoup(res, features="html5lib")
            parsed_str = str(parsed)
            PixivHelper.print_and_log("info", f'Logging in, return url: {res.geturl()}')
            res.close()
            parsed.decompose()
            del parsed

            if "logout.php" in parsed_str:
                result = True
            if "pixiv.user.loggedIn = true" in parsed_str:
                result = True
            if "_gaq.push(['_setCustomVar', 1, 'login', 'yes'" in parsed_str:
                result = True
            if "var dataLayer = [{ login: 'yes'," in parsed_str:
                result = True

            if result:
                PixivHelper.print_and_log('info', 'Login successful.')
                PixivHelper.get_logger().info('Logged in using cookie')
                self.getMyId(parsed_str)
                temp_locale = str(res.geturl()).replace('https://www.pixiv.net', '').replace('/', '')
                if len(temp_locale) > 0:
                    self._locale = '/' + temp_locale
                PixivHelper.get_logger().info('Locale = %s', self._locale)
            else:
                PixivHelper.get_logger().info('Failed to log in using cookie')
                PixivHelper.print_and_log('info', 'Cookie already expired/invalid.')

        return result
```

**Comment by ach4ndi** [comment]
for "Unable to get User Id, please check your cookie" issue, is seems the issue on the account session itself, either get restricted or Cloudflare issue. is funny enough older session for another account is able to login (is already more than 8 month). Maybe can using another account?

**Comment by jian96** [comment]
Just got this issue, was still using it a week ago, suddenly I get the "cannot get userId" issue now. I tried relogging and still doesn't work. My old session was about a year old

**Comment by sk19vn** [comment]
I had been having this issue with fanbox for a while but now it is happening with the main pixiv site as well

`Unable to get User Id, please check your cookie.
Please follow the instruction in https://github.com/Nandaka/PixivUtil2/issues/814#issuecomment-711182644
Error at doLogin(): (<class 'PixivException.PixivException'>, PixivException('Unable to get User Id, please check your cookie.'), <traceback object at 0x0000012ECBE22800>)
Traceback (most recent call last):
  File "PixivUtil2.py", line 1524, in doLogin
  File "PixivBrowserFactory.py", line 367, in loginUsingCookie
  File "PixivBrowserFactory.py", line 577, in getMyId
PixivException.PixivException: PixivException(100 Unable to get User Id, please check your cookie., hasDumpPage=Y)

Cannot Login!`

**Comment by ChibiChanNya** [comment]
> def loginUsingCookie(self, login_cookie=None):
>         """  Log in to Pixiv using saved cookie, return True if success """
>         result = False
> 
>         if login_cookie is None or len(login_cookie) == 0:
>             login_cookie = self._config.cookie
> 
>         if len(login_cookie) > 0:
>             PixivHelper.print_and_log('info', 'Trying to log in with saved cookie')
>             self.clearCookie()
> 
>             # Copying solution from #1342 for pixiv.net
>             if self._config.cf_clearance != "":
>                 ck1 = http.cookiejar.Cookie(version=0, name='cf_clearance', value=self._config.cf_clearance, port=None,
>                                             port_specified=False, domain='www.pixiv.net', domain_specified=True,
>                                             domain_initial_dot=False, path='/', path_specified=True,
>                                             secure=False, expires=None, discard=True, comment=None,
>                                             comment_url=None, rest={'HttpOnly': None}, rfc2109=False)
>                 self.addCookie(ck1)
>             if self._config.cf_bm != "":
>                 ck2 = http.cookiejar.Cookie(version=0, name='__cf_bm', value=self._config.cf_bm, port=None,
>                                             port_specified=False, domain='www.pixiv.net', domain_specified=True,
>                                             domain_initial_dot=False, path='/', path_specified=True,
>                                             secure=False, expires=None, discard=True, comment=None,
>                                             comment_url=None, rest={'HttpOnly': None}, rfc2109=False)
>                 self.addCookie(ck2)
> 
> 
>             self._loadCookie(login_cookie, "pixiv.net")
>             res = self.open_with_retry('https://www.pixiv.net')  # + self._locale)
>             parsed = BeautifulSoup(res, features="html5lib")
>             parsed_str = str(parsed)
>             PixivHelper.print_and_log("info", f'Logging in, return url: {res.geturl()}')
>             res.close()
>             parsed.decompose()
>             del parsed
> 
>             if "logout.php" in parsed_str:
>                 result = True
>             if "pixiv.user.loggedIn = true" in parsed_str:
>                 result = True
>             if "_gaq.push(['_setCustomVar', 1, 'login', 'yes'" in parsed_str:
>                 result = True
>             if "var dataLayer = [{ login: 'yes'," in parsed_str:
>                 result = True
> 
>             if result:
>                 PixivHelper.print_and_log('info', 'Login successful.')
>                 PixivHelper.get_logger().info('Logged in using cookie')
>                 self.getMyId(parsed_str)
>                 temp_locale = str(res.geturl()).replace('https://www.pixiv.net', '').replace('/', '')
>                 if len(temp_locale) > 0:
>                     self._locale = '/' + temp_locale
>                 PixivHelper.get_logger().info('Locale = %s', self._locale)
>             else:
>                 PixivHelper.get_logger().info('Failed to log in using cookie')
>                 PixivHelper.print_and_log('info', 'Cookie already expired/invalid.')
> 
>         return result

Been messing around with this though I'm a newcomer to the project.
I tried using the method of passing the entire original cookie string from the headers and somehow I'm still getting a 403.
I figured that brute force solution would do it, but I guess Pixiv is staying ahead of the game.
